---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes
  notify: restart apache

- name: Install PHP and extensions
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Ensure Apache is started
  service:
    name: apache2
    state: started
    enabled: yes